-- Inserção de 20 Registros com Nomes Reais de Categorias
INSERT INTO categories (name, active)
VALUES ('Electronics', TRUE),
       ('Clothing', TRUE),
       ('Home Appliances', TRUE),
       ('Books', TRUE),
       ('Sports Equipment', TRUE),
       ('Toys', TRUE),
       ('Furniture', TRUE),
       ('Jewelry', TRUE),
       ('Beauty Products', TRUE),
       ('Automotive', TRUE),
       ('Health & Wellness', TRUE),
       ('Office Supplies', TRUE),
       ('Garden Tools', TRUE),
       ('Pet Supplies', TRUE),
       ('Music', TRUE),
       ('Movies', TRUE),
       ('Tools & Hardware', TRUE),
       ('Outdoor Gear', TRUE),
       ('Food & Beverages', TRUE),
       ('Stationery', TRUE);

-- Inserção de 20 Registros com Nomes Reais de Marcas
INSERT INTO brands (name, active)
VALUES ('Nike', TRUE),
       ('Adidas', TRUE),
       ('Puma', TRUE),
       ('Reebok', TRUE),
       ('Under Armour', TRUE),
       ('New Balance', TRUE),
       ('Asics', TRUE),
       ('Converse', TRUE),
       ('Vans', TRUE),
       ('Fila', TRUE),
       ('Skechers', TRUE),
       ('Saucony', TRUE),
       ('Brooks', TRUE),
       ('Hoka One One', TRUE),
       ('Mizuno', TRUE),
       ('On Running', TRUE),
       ('Merrell', TRUE),
       ('Columbia', TRUE),
       ('The North Face', TRUE),
       ('Patagonia', TRUE);

-- Inserção de 20 Registros com Exemplos de Produtos Reais
INSERT INTO products (sku, name, description, category_id, brand_id, price, active)
VALUES ('SPX-1234', 'Smartphone XYZ', 'Latest model with advanced features', 1, 1, 699.99, TRUE),
       ('RS-5678', 'Running Shoes', 'Comfortable shoes for running and exercise', 5, 2, 89.99, TRUE),
       ('BL-9101', 'Blender', 'High-speed blender for smoothies', 3, 3, 129.99, TRUE),
       ('NB-1122', 'Novel Book', 'Bestselling fiction novel', 4, 4, 14.99, TRUE),
       ('BK-3344', 'Basketball', 'Official size and weight basketball', 5, 5, 29.99, TRUE),
       ('TB-5566', 'Teddy Bear', 'Soft and cuddly teddy bear for kids', 6, 6, 19.99, TRUE),
       ('OC-7788', 'Office Chair', 'Ergonomic office chair with adjustable height', 7, 7, 199.99, TRUE),
       ('GN-9900', 'Gold Necklace', 'Elegant gold necklace for special occasions', 8, 8, 499.99, TRUE),
       ('SH-1234', 'Shampoo', 'High-quality shampoo for all hair types', 9, 9, 7.99, TRUE),
       ('CT-5678', 'Car Tire', 'Durable all-season car tire', 10, 10, 89.99, TRUE),
       ('VT-9101', 'Vitamins', 'Daily multivitamin supplement', 11, 11, 24.99, TRUE),
       ('PP-1122', 'Printer Paper', 'A4 printer paper, 500 sheets', 12, 12, 9.99, TRUE),
       ('LM-3344', 'Lawn Mower', 'Gas-powered lawn mower for large yards', 13, 13, 399.99, TRUE),
       ('CF-5566', 'Cat Food', 'High-nutrition food for cats', 14, 14, 29.99, TRUE),
       ('GT-7788', 'Guitar', 'Acoustic guitar with carrying case', 15, 15, 149.99, TRUE),
       ('BD-9900', 'Blu-ray Disc', 'Latest blockbuster movie on Blu-ray', 16, 16, 19.99, TRUE),
       ('DR-1234', 'Drill', 'Cordless power drill with multiple attachments', 17, 17, 89.99, TRUE),
       ('CT-5678', 'Camping Tent', 'Durable and easy-to-set-up camping tent', 18, 18, 159.99, TRUE),
       ('CM-9101', 'Coffee Maker', 'Single-serve coffee maker with programmable settings', 19, 19, 59.99, TRUE),
       ('NB-1123', 'Notebook', 'High-quality notebook for writing and notes', 20, 20, 14.99, TRUE);